### POST request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Ngoc Cam",
  "email": "ngoccam@example.com",
  "address": "Quang Ngai",
  "dateOfBirth": "2002-01-20",
  "registeredDate": "2025-04-20"
}

###